# Generated by Django 5.2.1 on 2025-05-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0003_remove_task_created_at_remove_task_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('URGENT', 'Urgent')], default='LOW', max_length=20),
        ),
    ]
