# Generated by Django 5.2.1 on 2025-05-16 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0004_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to=settings.AUTH_USER_MODEL)),
                ('task_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_task', to='DRF.task')),
            ],
        ),
    ]
