# Generated by Django 4.2.6 on 2025-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0005_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPagination', models.IntegerField(default=10)),
            ],
        ),
    ]
