# Generated by Django 5.2.1 on 2025-05-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0008_task_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
