# Generated by Django 5.2.1 on 2025-05-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0010_user_groups_user_last_login_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Required. 128 characters or fewer. Alphanumeric characters and @/./+/-/_ only.', max_length=128, verbose_name='password'),
        ),
    ]
