# Generated by Django 5.2.1 on 2025-06-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
