# Generated by Django 5.1 on 2025-06-11 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0012_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='cambio_user',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='task_assigned',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='new_task',
            field=models.ForeignKey(blank=True, help_text='Tarea después del cambio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_task', to='DRF.task'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='old_task',
            field=models.ForeignKey(blank=True, help_text='Tarea antes del cambio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_task', to='DRF.task'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='user_id',
            field=models.ForeignKey(default=1, help_text='Usuario que realiza el cambio', on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
