# Generated by Django 5.1 on 2025-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0013_remove_auditoria_cambio_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='new_task',
            field=models.CharField(help_text='Tarea despues del cambio', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='old_task',
            field=models.CharField(help_text='Tarea antes del cambio', max_length=100),
        ),
    ]
